---
- name: install node and npm
  hosts: 159.89.1.54
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3000
    - name: Install nodejs and npm
      apt: 
        pkg:
        - node
        - npm 

- name: Create new linux user
  hosts: 159.89.1.54
  vars_files:
    - fox-vars
  tasks:
  - name: Create Linux user
    user:
      name: "{{name}}"
      comment: Fox user  
      group: admin

- name: Deploy nodejs app
  hosts: 159.89.1.54
  become: True 
  become_user: "{{linux_name}}"
  vars_files:
    - fox-vars
  tasks:
    -  name: Unpack the nodejs file
       unarchive:
        src: "{{location}}//nodejs-app-{{version}}.tgz"
        dest: "{{user_home}}"
    - name: Install dependencies
      npm:
        path: "{{user_home}}/package"
    - name: Start the application
      command: 
        chdir: "{{user_home}}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep fox
      register: app_status
    - debug: msg={{app_status.stdout_lines}}

        