---
-  name: Install java and net tools
   host: nexus_server
   tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3000
    - name: Install Java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and unapack Nexus installer
  hosts: nexus_server
  tasks: 
  - name: Check nexus folder stat
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Download Nexus
      get_url: 
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar nexus installer
        unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists
    - name: Find nexus folder
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      registry: find_result
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists

- name: Create nexus user to own nexus
  hosts: nexus_server
  tasks:
    - name: Ensure group nexus exists
      group:
        name: nexis
        state: present
    - name: Create nexus user
      user:
        name: nexus
        group: nexus
    - name: make nexus user owner of nexus folder
      file: 
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: make nexus user owner of sonatype-work folder
      file: 
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start nexus with nexus user
  hosts: nexus_server
  become: True
  become_user: nexus 
  tasks:
    - name: Set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^run_as_user=""'
        line: run_as_user="nexus"
    - name: Start nexus
      commands: /opt/nexus-3.28.1-01/bin/nexus start

- name: Verify nexus running
  hosts: nexus_server
  tasks:
  - name: Check with ps
    shell: ps aux | grep nexus
    register: app_status
  - debug: msg={{app_status.stdout_lines}}
  - name: wait one minute
    pause:
      minutes: 1
    name: Check with netstat
    shell: netstat -pint
    register: app_status
